#!/usr/bin/env python3
"""Build a VALID witness for the UNMODIFIED v0a_skeleton circuit (synthetic data only).

The circuit (arbitrum/poc/circuit, a verbatim copy of noir/v0a_skeleton) is NOT changed.
We only construct inputs that satisfy its asserts. The single non-trivial part is C1's
Schnorr signature (schnorr v0.4.0, Poseidon2/Grumpkin):

    e = Poseidon2([DST, R.x, P.x, P.y, M], 5)        # the challenge
    verify: s*G + e*P == R  and  Poseidon2([DST,(s*G+e*P).x,P.x,P.y,M]) == e

so to sign with secret key sk (P = sk*G) and nonce k (R = k*G):

    s = (k - e*sk) mod n        # n = Grumpkin group order (= BN254 base field q)

All Poseidon2 / Grumpkin values (P, R.x, C, ROOT, M, e) are computed by the Noir helper
crate (arbitrum/poc/helper) so they match the circuit's libraries byte-for-byte. This
script runs that helper, then finishes s and writes circuit/Prover.toml.
"""
import os
import re
import subprocess
import sys
from pathlib import Path

# ── field/group constants ───────────────────────────────────────────────────
# Grumpkin group order n == BN254 base-field modulus q. Scalars (sk, k, s) live mod n.
N = 21888242871839275222246405745257275088696311157297823662689037894645226208583
M128 = 2 ** 128
MASK128 = M128 - 1

POC = Path(__file__).resolve().parents[1]            # arbitrum/poc
NARGO = os.path.expanduser("~/.nargo/bin/nargo")

# ── synthetic witness (NO real keys / PII) ──────────────────────────────────
sk = 1234567890123456789012345678901234567890        # signer secret key  (< n)
k  = 9876543210987654321098765432109876543210        # nonce              (< n)

fields = dict(
    enc_seller_tin=1001, enc_buyer_id=2002, enc_datetime=20260621, enc_invoice=42,
    items=7, salt=123456789,
)
# C3 VAT (round-half-up): vat_amount*10000 + r == vat_base*rate_bp + 5000, 0<=r<10000
amounts = dict(margin=3000, vat_base=10000, vat_amount=2100, rate_bp=2100, total=12100, r=5000)
digest_hi, digest_lo = 11259375, 1193046             # opaque digest limbs (public, synthetic)
siblings = [11, 22, 33, 44, 55, 66, 77]
path_bits = [True, False, True, False, False, False, False]


def limbs(x):
    return x % M128, x // M128


def write_helper_toml():
    sk_lo, sk_hi = limbs(sk); k_lo, k_hi = limbs(k)
    lines = [
        f'sk_lo = "{sk_lo}"', f'sk_hi = "{sk_hi}"',
        f'k_lo = "{k_lo}"', f'k_hi = "{k_hi}"',
        *(f'{key} = "{val}"' for key, val in fields.items()),
        *(f'{key} = "{val}"' for key, val in amounts.items() if key != "r"),  # helper ignores r
        f'digest_hi = "{digest_hi}"', f'digest_lo = "{digest_lo}"',
        'siblings = [' + ', '.join(f'"{s}"' for s in siblings) + ']',
        'path_bits = [' + ', '.join('true' if b else 'false' for b in path_bits) + ']',
    ]
    (POC / "helper" / "Prover.toml").write_text("\n".join(lines) + "\n")


def run_helper():
    out = subprocess.run([NARGO, "execute"], cwd=POC / "helper",
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("helper nargo execute failed:\n" + out.stdout + out.stderr)
    vals = {}
    for m in re.finditer(r'^(PK_X|PK_Y|R_X|C|ROOT|M|E)=(0x[0-9a-fA-F]+)$', out.stdout, re.M):
        vals[m.group(1)] = int(m.group(2), 16)
    need = {"PK_X", "PK_Y", "R_X", "C", "ROOT", "M", "E"}
    if need - vals.keys():
        sys.exit("helper output missing: " + ", ".join(need - vals.keys()))
    return vals


def write_circuit_toml(v):
    e = v["E"]
    s = (k - e * sk) % N                              # finish the Schnorr signature
    s_lo, s_hi = limbs(s); e_lo, e_hi = limbs(e)
    lines = [
        "# AUTO-GENERATED by scripts/gen_inputs.py — SYNTHETIC, valid witness for v0a_skeleton.",
        f'pk_x = "{hex(v["PK_X"])}"',
        f'pk_y = "{hex(v["PK_Y"])}"',
        f'sellers_root = "{hex(v["ROOT"])}"',
        f'd_hi = "{digest_hi}"',
        f'd_lo = "{digest_lo}"',
        f'c = "{hex(v["C"])}"',
        *(f'{key} = "{val}"' for key, val in fields.items() if key != "salt"),
        *(f'{key} = "{val}"' for key, val in amounts.items()),
        f'salt = "{fields["salt"]}"',
        f'sig_s_lo = "{s_lo}"', f'sig_s_hi = "{s_hi}"',
        f'sig_e_lo = "{e_lo}"', f'sig_e_hi = "{e_hi}"',
        'siblings = [' + ', '.join(f'"{s_}"' for s_ in siblings) + ']',
        'path_bits = [' + ', '.join('true' if b else 'false' for b in path_bits) + ']',
    ]
    (POC / "circuit" / "Prover.toml").write_text("\n".join(lines) + "\n")
    return s, e


def main():
    write_helper_toml()
    v = run_helper()
    s, e = write_circuit_toml(v)
    print("helper values (hex):")
    for k_ in ("PK_X", "PK_Y", "R_X", "C", "ROOT", "M", "E"):
        print(f"  {k_:5} = {hex(v[k_])}")
    print(f"\nsignature: s = (k - e*sk) mod n")
    print(f"  s = {hex(s)}")
    print(f"  e = {hex(e)}")
    print(f"\nwrote {POC/'circuit'/'Prover.toml'}")
    print("public inputs order: [pk_x, pk_y, sellers_root, d_hi, d_lo, c]")


if __name__ == "__main__":
    main()
