//! PRIVA-FISC × STRK20 — VAT-on-ciphertext PoC.
//!
//! Proves, with a real ZK Sigma proof, the ADDITIVE VAT consistency of a Tongo-style
//! confidential payment — `total = vat_base + vat_amount` — while the amount stays ENCRYPTED:
//!
//!   * amounts are additively-homomorphic ElGamal ciphertexts over the Stark curve
//!     (the exact scheme Tongo/`she` use):  Enc(b; r) = (b·G + r·Y , r·G);
//!   * the additive identity `total = vat_base + vat_amount` is proven ON THE CIPHERTEXTS via
//!     SHE `SameEncryption`:  Enc(total) and Enc(vat_base) ⊕ Enc(vat_amount) encrypt the
//!     same value — no decryption, amount never revealed;
//!   * the encrypted amount is BOUND to the receipt commitment C (C2 Poseidon, via the
//!     proof prefix) and to the authority attestation (C1 Stark-curve ECDSA over a
//!     message that contains C, the registry root, and the receipt digest D);
//!   * the seller is proven to be in the authority registry (C4 Poseidon Merkle).
//!
//! SCOPE — what this PoC does NOT prove (stated up front, not buried):
//!   * the MULTIPLICATIVE rate relation `vat_amount = vat_base·rate/10000` is OUT OF SCOPE
//!     (needs an OR-proof over statutory rates or a DLEQ-bound arithmetic proof — recon §C.6).
//!     A receipt with the right sum but the wrong rate would pass here.
//!   * `SameEncryption` proves equality of the plaintext SCALARS MODULO THE CURVE ORDER
//!     (≈2^251). There is no range proof, so integer-level soundness (no modular wrap, amounts
//!     in [0, 2^k)) is NOT enforced — `she`'s `Range`/`Bit` gadgets would close this. See the
//!     `documents_modular_equality_limitation` test, which shows a wrapped total is accepted.
//!   * `pk_a` and `r_reg` are trusted public inputs (SPEC §2): the authority signature is only
//!     as meaningful as an out-of-band binding of `pk_a` to the real authority.
//!
//! Verifier-side uses the real `she` library (v0.4.0, the SHE Sigma-protocol toolbox that
//! backs Tongo). The Sigma proof is generated by an off-chain prover; the in-Cairo prover
//! helpers below mirror `she`/`tongo`'s own `prover_for_testing` idioms so the PoC is
//! end-to-end. `prove_vat` is a TEST/DEMO prover (test-seeded nonces) — NOT production: a real
//! deployment needs fresh CSPRNG nonces and a hardened prover. SYNTHETIC data — no real key/PII.

use core::ec::stark_curve::{GEN_X, GEN_Y, ORDER};
use core::ec::{EcPoint, EcPointTrait, EcStateTrait, NonZeroEcPoint};
use core::ecdsa::check_ecdsa_signature;
use core::poseidon::poseidon_hash_span;
use she::protocols::SameEncryption::{
    SameEncryptionInputs, SameEncryptionProofWithPrefix, verify_with_prefix,
};
use she::utils::{compute_challenge, compute_s};
use crate::{leaf_of, merkle_root};

// Domain-separation tags.
pub const DS_COMMIT: felt252 = 'PFISC_COMMIT_strk20';
pub const DS_ATTEST: felt252 = 'PFISC_ATTEST_strk20';
pub const DS_VATBIND: felt252 = 'PFISC_VATBIND_strk20';

/// The Stark-curve generator G as a non-zero point.
pub fn g_nz() -> NonZeroEcPoint {
    EcPointTrait::new_nz(GEN_X, GEN_Y).unwrap()
}

/// Modular addition over the curve order (for combining ElGamal randomness without
/// felt-field wraparound — `r_base + r_tax` can exceed the field prime).
pub fn add_mod_order(a: felt252, b: felt252) -> felt252 {
    let a256: u256 = a.into();
    let b256: u256 = b.into();
    let n: u256 = ORDER.into();
    let s = (a256 + b256) % n;
    s.try_into().unwrap()
}

// ===========================================================================
// ElGamal ciphertext over the Stark curve: (L, R) = (b·G + r·Y , r·G)
//   Y = recipient/payment public key. Additively homomorphic.
// ===========================================================================
#[derive(Drop, Copy)]
pub struct Cipher {
    pub L: NonZeroEcPoint,
    pub R: NonZeroEcPoint,
}

/// Enc(b; r) under key `y`.
pub fn encrypt(b: felt252, r: felt252, y: NonZeroEcPoint) -> Cipher {
    let g = g_nz();
    let mut st = EcStateTrait::init();
    st.add_mul(b, g);
    st.add_mul(r, y);
    let l = st.finalize_nz().unwrap();
    let rr: NonZeroEcPoint = g.into().mul(r).try_into().unwrap();
    Cipher { L: l, R: rr }
}

/// Homomorphic add: Enc(a) ⊕ Enc(b) = (L_a+L_b , R_a+R_b) = Enc(a+b).
/// Returns `None` if either component sum is the point at infinity — ct_base/ct_tax are
/// PUBLIC verifier inputs, so an adversary could pick L_a = -L_b; we reject rather than panic.
pub fn cipher_add(a: Cipher, b: Cipher) -> Option<Cipher> {
    let al: EcPoint = a.L.into();
    let bl: EcPoint = b.L.into();
    let ar: EcPoint = a.R.into();
    let br: EcPoint = b.R.into();
    let l: NonZeroEcPoint = (al + bl).try_into()?;
    let r: NonZeroEcPoint = (ar + br).try_into()?;
    Option::Some(Cipher { L: l, R: r })
}

// ===========================================================================
// Public statement + private witness.
// ===========================================================================
#[derive(Drop, Copy)]
pub struct FiscStatement {
    pub y: NonZeroEcPoint, // payment public key (amounts encrypted under it)
    pub ct_base: Cipher, // Enc(vat_base)
    pub ct_tax: Cipher, // Enc(vat_amount)
    pub ct_total: Cipher, // Enc(total)
    pub commitment: felt252, // C2 — public receipt commitment
    pub r_reg: felt252, // C4 — authority registry Merkle root
    pub d_hi: felt252, // C5 — receipt digest D (disclosed, v0-A)
    pub d_lo: felt252,
    pub datetime: felt252,
    pub invoice_no: felt252,
    pub pk_a: felt252 // C1 — authority public key (Stark-curve x-coord)
}

/// Private receipt metadata that C2 binds (amounts themselves stay encrypted).
#[derive(Drop, Copy)]
pub struct FiscWitness {
    pub seller_tin: felt252,
    pub buyer_id: felt252,
    pub items_hash: felt252,
    pub margin: felt252,
    pub rate_bp: felt252,
    pub salt: felt252,
}

#[derive(Drop, Copy, PartialEq)]
pub enum FiscError {
    CommitmentMismatch, // C2: recomputed C ≠ public C
    MalformedCiphertext, // adversarial public ciphertext (homomorphic sum is point-at-infinity)
    VatProofNotBound, // VAT proof prefix not bound to this receipt
    VatNotConsistent, // SameEncryption failed → total ≠ base + tax (mod ORDER)
    BadAttestation, // C1: authority ECDSA invalid
    NotRegistered // C4: seller ∉ registry
}

// ===========================================================================
// C2 — receipt commitment binding the (encrypted) amounts + private metadata.
// ===========================================================================
fn coords(p: NonZeroEcPoint) -> (felt252, felt252) {
    p.coordinates()
}

pub fn commit_fisc(w: @FiscWitness, st: @FiscStatement) -> felt252 {
    let (yx, yy) = coords(*st.y);
    let (blx, bly) = coords(*st.ct_base.L);
    let (brx, bry) = coords(*st.ct_base.R);
    let (tlx, tly) = coords(*st.ct_tax.L);
    let (trx, tr_y) = coords(*st.ct_tax.R);
    let (zlx, zly) = coords(*st.ct_total.L);
    let (zrx, zry) = coords(*st.ct_total.R);
    poseidon_hash_span(
        array![
            DS_COMMIT, *w.seller_tin, *w.buyer_id, *w.items_hash, *w.margin, *w.rate_bp, *w.salt,
            yx, yy, blx, bly, brx, bry, tlx, tly, trx, tr_y, zlx, zly, zrx, zry,
        ]
            .span(),
    )
}

/// Prefix that binds the VAT Sigma proof to this exact receipt (C, registry, D).
pub fn vat_binding_prefix(st: @FiscStatement) -> felt252 {
    poseidon_hash_span(
        array![DS_VATBIND, *st.commitment, *st.r_reg, *st.d_hi, *st.d_lo].span(),
    )
}

/// C1 binding message: authority signs (D, C, registry root, anti-replay).
pub fn binding_message(st: @FiscStatement) -> felt252 {
    poseidon_hash_span(
        array![
            DS_ATTEST, *st.d_hi, *st.d_lo, *st.commitment, *st.r_reg, *st.datetime, *st.invoice_no,
        ]
            .span(),
    )
}

// ===========================================================================
// THE VERIFIER — proves a confidential payment was correctly taxed.
// ===========================================================================
pub fn verify_taxed_payment(
    st: @FiscStatement,
    w: @FiscWitness,
    vat_proof: SameEncryptionProofWithPrefix,
    sig_r: felt252,
    sig_s: felt252,
    siblings: Span<felt252>,
    path_bits: Span<bool>,
) -> Result<(), FiscError> {
    // C2 — recompute the commitment from witness + public ciphertexts.
    if commit_fisc(w, st) != *st.commitment {
        return Result::Err(FiscError::CommitmentMismatch);
    }

    // VAT proof must be bound to THIS receipt (prevents lifting a proof onto another).
    if vat_proof.prefix != vat_binding_prefix(st) {
        return Result::Err(FiscError::VatProofNotBound);
    }

    // VAT-on-ciphertext — recompute CT_sum = CT_base ⊕ CT_tax, then prove (in ZK) that
    // CT_sum and CT_total encrypt the SAME value  ⇒  total = vat_base + vat_amount (mod ORDER).
    // NB: SameEncryption certifies equality of the plaintext SCALARS mod the curve order; it is
    // NOT an integer-range check (see module-level SCOPE note — a wrapped total can satisfy it).
    let ct_sum = match cipher_add(*st.ct_base, *st.ct_tax) {
        Option::Some(c) => c,
        Option::None => { return Result::Err(FiscError::MalformedCiphertext); },
    };
    // y1 = y2 = st.y: both ciphertexts share the payment key, so SameEncryption is used in its
    // single-key form to prove plaintext equality of CT_sum and CT_total.
    let se_inputs = SameEncryptionInputs {
        L1: ct_sum.L,
        R1: ct_sum.R,
        L2: *st.ct_total.L,
        R2: *st.ct_total.R,
        g: g_nz(),
        y1: *st.y,
        y2: *st.y,
    };
    if verify_with_prefix(se_inputs, vat_proof).is_err() {
        return Result::Err(FiscError::VatNotConsistent);
    }

    // C1 — authority Stark-curve ECDSA over M = H(D, C, registry, anti-replay).
    // Trust model (SPEC §2): `st.pk_a` is the authority public key, a trusted public input —
    // a deployment must pin it to the real authority (out of band), else C1/C4 are vacuous.
    let m = binding_message(st);
    if !check_ecdsa_signature(m, *st.pk_a, sig_r, sig_s) {
        return Result::Err(FiscError::BadAttestation);
    }

    // C4 — seller is in the authority registry (root anchored by C1's signature over M).
    let root = merkle_root(leaf_of(*w.seller_tin), siblings, path_bits);
    if root != *st.r_reg {
        return Result::Err(FiscError::NotRegistered);
    }

    Result::Ok(())
}

/// Instruction-level wrapper: panics (assertion halt) unless the payment proof is valid.
pub fn assert_taxed_payment(
    st: @FiscStatement,
    w: @FiscWitness,
    vat_proof: SameEncryptionProofWithPrefix,
    sig_r: felt252,
    sig_s: felt252,
    siblings: Span<felt252>,
    path_bits: Span<bool>,
) {
    match verify_taxed_payment(st, w, vat_proof, sig_r, sig_s, siblings, path_bits) {
        Result::Ok(()) => {},
        Result::Err(e) => {
            let code: felt252 = match e {
                FiscError::CommitmentMismatch => 'C2_COMMIT_MISMATCH',
                FiscError::MalformedCiphertext => 'MALFORMED_CIPHERTEXT',
                FiscError::VatProofNotBound => 'VAT_PROOF_NOT_BOUND',
                FiscError::VatNotConsistent => 'VAT_NOT_CONSISTENT',
                FiscError::BadAttestation => 'C1_BAD_ATTESTATION',
                FiscError::NotRegistered => 'C4_NOT_REGISTERED',
            };
            core::panic_with_felt252(code);
        },
    }
}

// ===========================================================================
// OFF-CHAIN PROVER — TEST/DEMO ONLY (synthetic). Mirrors she/tongo `prover_for_testing`.
// NOT a production prover: callers pass test-seeded nonces (kb,kr1,kr2) and the witness in
// the clear. A real prover MUST draw kb/kr1/kr2 from a CSPRNG (fresh, never reused across
// statements) or it leaks the witness amounts; the SHE soundness/ZK holds only then.
// Builds the SameEncryption proof that CT_sum and CT_total encrypt the same value.
//   b  = vat_base + vat_amount (= total when honest)
//   r1 = r_base + r_tax  (randomness of CT_sum, mod ORDER)
//   r2 = r_total         (randomness of CT_total)
// ===========================================================================
pub fn prove_vat(
    b: felt252, r1: felt252, r2: felt252, y: NonZeroEcPoint, prefix: felt252, kb: felt252,
    kr1: felt252, kr2: felt252,
) -> SameEncryptionProofWithPrefix {
    let g = g_nz();

    // commitments  AL1 = kb·G + kr1·Y , AR1 = kr1·G , AL2 = kb·G + kr2·Y , AR2 = kr2·G
    let mut st = EcStateTrait::init();
    st.add_mul(kb, g);
    st.add_mul(kr1, y);
    let al1 = st.finalize_nz().unwrap();
    let ar1: NonZeroEcPoint = g.into().mul(kr1).try_into().unwrap();

    let mut st2 = EcStateTrait::init();
    st2.add_mul(kb, g);
    st2.add_mul(kr2, y);
    let al2 = st2.finalize_nz().unwrap();
    let ar2: NonZeroEcPoint = g.into().mul(kr2).try_into().unwrap();

    // Fiat-Shamir challenge bound to the prefix (same as she verify_with_prefix order).
    let c = compute_challenge(prefix, array![al1, ar1, al2, ar2]);

    // responses  sb = kb + c·b , sr1 = kr1 + c·r1 , sr2 = kr2 + c·r2  (mod ORDER)
    let sb = compute_s(kb, b, c);
    let sr1 = compute_s(kr1, r1, c);
    let sr2 = compute_s(kr2, r2, c);

    SameEncryptionProofWithPrefix { AL1: al1, AR1: ar1, AL2: al2, AR2: ar2, prefix, sb, sr1, sr2 }
}
